site: Kusa
title: Kusa
description: >-
  just a minimalist, personal blog
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Europe/London
repo: https://github.com/Kusa/Kusa # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Kusa
  bio: Kusa Author
  about_text: Hi There. I'm Kusa. I'm a clean and lightweight jekyll theme. I have a light and dark theme for your eyes.
  username: Kusa # author username
  #profile_picture: https://avatars.githubusercontent.com/u/66906402 # profile_picture url / or use assets/images/author.jpg
  github: Kusa # github username
  twitter: Kusa # twitter username
  email: kusa-email@email.com # email adress


# Homepage Greeting
greetings:  Hi 👋


url: "https://cypherpunksamurai.github.io" # main hosting url
#url: "http://localhost:4000" # localhost debug
baseurl: "/Kusa-Jekyll" # default to "". use only if blog is hosted in subdirectory on the server
# baseurl: "" # localhost debug
permalink: pretty


tag_page_layout: tag
tag_page_dir: tag



markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  #- jekyll-tagging
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


