# --------------------
#
#   Kusa Jekyll
#
# --------------------

# Author: CypherpunkSamurai

# _config.yml - config for jekyll site

# site name
site: Kusa
# site title
title: Kusa
# site description
description: >-
  just a minimalist, personal blog


# Homepage Greeting
greetings:  Hi 👋
# Default Theme
data-theme: dark # default theme "dark" | "light"


# use play font and source code pro
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900
# language
lang: en-US
# timezone
timezone: Europe/London
repo: https://github.com/CypherpunkSamurai/Kusa-Jekyll # site repo [optional]



# Author for Posts
author:
  # Author Name
  name: Kusa
  # Author Bio
  bio: Kusa Author
  about_text: Hi There. I'm Kusa. I'm a clean and lightweight jekyll theme. I have a light and dark theme for your eyes.
  username: Kusa # author username
  #profile_picture: https://avatars.githubusercontent.com/u/66906402 # profile_picture url / or use assets/images/author.jpg
  github: Kusa # github username
  twitter: Kusa # twitter username
  email: kusa-email@email.com # email adress


# Site URL settings
url: "https://cypherpunksamurai.github.io" # main hosting url
baseurl: "/Kusa-Jekyll" # default to "". use only if blog is hosted in subdirectory on the server
# url: "http://localhost:4000" # localhost debug
# baseurl: "" # localhost debug
permalink: pretty

# Auto tagging Settings
tag_page_layout: tag
tag_page_dir: tag


# -------------------
#
#   DO NOT TOUCH
# 
# advanced users only
#
# --------------------

# rendering settings

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  #- jekyll-tagging
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


